$(function(){
$(".myfix-1").click(function(){
$("#box").load("./data/post-1.html");});
$(".myfix-2").click(function(){
$("#box").load("./data/post-2.html");});
$(".myfix-3").click(function(){
$("#box").load("./data/post-3.html");});
$(".myfix-4").click(function(){
$("#box").load("./data/post-4.html");});
$(".myfix-5").click(function(){
$("#box").load("./data/post-5.html");});
$(".myfix-6").click(function(){
$("#box").load("./data/post-6.html");});
$(".myfix-7").click(function(){
$("#box").load("./data/post-7.html");});
$(".myfix-8").click(function(){
$("#box").load("./data/post-8.html");});
$(".myfix-9").click(function(){
$("#box").load("./data/post-9.html");});
$(".myfix-10").click(function(){
$("#box").load("./data/post-10.html");});
$(".myfix-11").click(function(){
$("#box").load("./data/post-11.html");});
$(".myfix-12").click(function(){
$("#box").load("./data/post-12.html");});
});
