$(function(){
$(".myfix-1").click(function(){
$("#box").load("./data/post-1");});
$(".myfix-2").click(function(){
$("#box").load("./data/post-2");});
$(".myfix-3").click(function(){
$("#box").load("./data/post-3");});
$(".myfix-4").click(function(){
$("#box").load("./data/post-4");});
$(".myfix-5").click(function(){
$("#box").load("./data/post-5");});
$(".myfix-6").click(function(){
$("#box").load("./data/post-6");});
$(".myfix-7").click(function(){
$("#box").load("./data/post-7");});
$(".myfix-8").click(function(){
$("#box").load("./data/post-8");});
$(".myfix-9").click(function(){
$("#box").load("./data/post-9");});
$(".myfix-10").click(function(){
$("#box").load("./data/post-10");});
$(".myfix-11").click(function(){
$("#box").load("./data/post-11");});
$(".myfix-12").click(function(){
$("#box").load("./data/post-12");});
$(".myfix-13").click(function(){
$("#box").load("./data/post-13");});
$(".myfix-14").click(function(){
$("#box").load("./data/post-14");});
$(".myfix-15").click(function(){
$("#box").load("./data/post-15");});
$(".myfix-16").click(function(){
$("#box").load("./data/post-16");});
$(".myfix-17").click(function(){
$("#box").load("./data/post-17");});
$(".myfix-18").click(function(){
$("#box").load("./data/post-18");});
$(".myfix-19").click(function(){
$("#box").load("./data/post-19");});
$(".myfix-20").click(function(){
$("#box").load("./data/post-20");});
$(".myfix-21").click(function(){
$("#box").load("./data/post-21");});
$(".myfix-22").click(function(){
$("#box").load("./data/post-22");});
$(".myfix-23").click(function(){
$("#box").load("./data/post-23");});
$(".myfix-24").click(function(){
$("#box").load("./data/post-24");});
$(".myfix-25").click(function(){
$("#box").load("./data/post-25");});
$(".myfix-26").click(function(){
$("#box").load("./data/post-26");});
$(".myfix-27").click(function(){
$("#box").load("./data/post-27");});
$(".myfix-28").click(function(){
$("#box").load("./data/post-28");});
$(".myfix-29").click(function(){
$("#box").load("./data/post-29");});
$(".myfix-30").click(function(){
$("#box").load("./data/post-30");});
$(".myfix-31").click(function(){
$("#box").load("./data/post-31");});
$(".myfix-32").click(function(){
$("#box").load("./data/post-32");});
$(".myfix-33").click(function(){
$("#box").load("./data/post-33");});
$(".myfix-34").click(function(){
$("#box").load("./data/post-34");});
$(".myfix-35").click(function(){
$("#box").load("./data/post-35");});
$(".myfix-36").click(function(){
$("#box").load("./data/post-36");});
$(".myfix-37").click(function(){
$("#box").load("./data/post-37");});
$(".myfix-38").click(function(){
$("#box").load("./data/post-38");});
$(".myfix-39").click(function(){
$("#box").load("./data/post-39");});
$(".myfix-40").click(function(){
$("#box").load("./data/post-40");});
$(".myfix-41").click(function(){
$("#box").load("./data/post-41");});
$(".myfix-42").click(function(){
$("#box").load("./data/post-42");});
$(".myfix-43").click(function(){
$("#box").load("./data/post-43");});
$(".myfix-44").click(function(){
$("#box").load("./data/post-44");});
$(".myfix-45").click(function(){
$("#box").load("./data/post-45");});
$(".myfix-46").click(function(){
$("#box").load("./data/post-46");});
$(".myfix-47").click(function(){
$("#box").load("./data/post-47");});
$(".myfix-48").click(function(){
$("#box").load("./data/post-48");});
$(".myfix-49").click(function(){
$("#box").load("./data/post-49");});
$(".myfix-50").click(function(){
$("#box").load("./data/post-50");});
$(".myfix-51").click(function(){
$("#box").load("./data/post-51");});
$(".myfix-52").click(function(){
$("#box").load("./data/post-52");});
$(".myfix-53").click(function(){
$("#box").load("./data/post-53");});
$(".myfix-54").click(function(){
$("#box").load("./data/post-54");});
$(".myfix-55").click(function(){
$("#box").load("./data/post-55");});
$(".myfix-56").click(function(){
$("#box").load("./data/post-56");});
$(".myfix-57").click(function(){
$("#box").load("./data/post-57");});
$(".myfix-58").click(function(){
$("#box").load("./data/post-58");});
$(".myfix-59").click(function(){
$("#box").load("./data/post-59");});
$(".myfix-60").click(function(){
$("#box").load("./data/post-60");});
$(".myfix-61").click(function(){
$("#box").load("./data/post-61");});
$(".myfix-62").click(function(){
$("#box").load("./data/post-62");});
$(".myfix-63").click(function(){
$("#box").load("./data/post-63");});
$(".myfix-64").click(function(){
$("#box").load("./data/post-64");});
$(".myfix-65").click(function(){
$("#box").load("./data/post-65");});
$(".myfix-66").click(function(){
$("#box").load("./data/post-66");});
$(".myfix-67").click(function(){
$("#box").load("./data/post-67");});
$(".myfix-68").click(function(){
$("#box").load("./data/post-68");});
$(".myfix-69").click(function(){
$("#box").load("./data/post-69");});
$(".myfix-70").click(function(){
$("#box").load("./data/post-70");});
$(".myfix-71").click(function(){
$("#box").load("./data/post-71");});
$(".myfix-72").click(function(){
$("#box").load("./data/post-72");});
$(".myfix-73").click(function(){
$("#box").load("./data/post-73");});
$(".myfix-74").click(function(){
$("#box").load("./data/post-74");});
$(".myfix-75").click(function(){
$("#box").load("./data/post-75");});
$(".myfix-76").click(function(){
$("#box").load("./data/post-76");});
$(".myfix-77").click(function(){
$("#box").load("./data/post-77");});
$(".myfix-78").click(function(){
$("#box").load("./data/post-78");});
$(".myfix-79").click(function(){
$("#box").load("./data/post-79");});
$(".myfix-80").click(function(){
$("#box").load("./data/post-80");});
$(".myfix-81").click(function(){
$("#box").load("./data/post-81");});
$(".myfix-82").click(function(){
$("#box").load("./data/post-82");});
$(".myfix-83").click(function(){
$("#box").load("./data/post-83");});
$(".myfix-84").click(function(){
$("#box").load("./data/post-84");});
$(".myfix-85").click(function(){
$("#box").load("./data/post-85");});
$(".myfix-86").click(function(){
$("#box").load("./data/post-86");});
$(".myfix-87").click(function(){
$("#box").load("./data/post-87");});
$(".myfix-88").click(function(){
$("#box").load("./data/post-88");});
$(".myfix-89").click(function(){
$("#box").load("./data/post-89");});
$(".myfix-90").click(function(){
$("#box").load("./data/post-90");});
$(".myfix-91").click(function(){
$("#box").load("./data/post-91");});
$(".myfix-92").click(function(){
$("#box").load("./data/post-92");});
$(".myfix-93").click(function(){
$("#box").load("./data/post-93");});
$(".myfix-94").click(function(){
$("#box").load("./data/post-94");});
$(".myfix-95").click(function(){
$("#box").load("./data/post-95");});
$(".myfix-96").click(function(){
$("#box").load("./data/post-96");});
$(".myfix-97").click(function(){
$("#box").load("./data/post-97");});
$(".myfix-98").click(function(){
$("#box").load("./data/post-98");});
$(".myfix-99").click(function(){
$("#box").load("./data/post-99");});
$(".myfix-100").click(function(){
$("#box").load("./data/post-100");});
});
