$(function(){
$(".myfix-1").click(function(){
$("#box").load("./data/post-1");});
$(".myfix-2").click(function(){
$("#box").load("./data/post-2");});
$(".myfix-3").click(function(){
$("#box").load("./data/post-3");});
$(".myfix-4").click(function(){
$("#box").load("./data/post-4");});
$(".myfix-5").click(function(){
$("#box").load("./data/post-5");});
$(".myfix-6").click(function(){
$("#box").load("./data/post-6");});
$(".myfix-7").click(function(){
$("#box").load("./data/post-7");});
$(".myfix-8").click(function(){
$("#box").load("./data/post-8");});
$(".myfix-9").click(function(){
$("#box").load("./data/post-9");});
$(".myfix-10").click(function(){
$("#box").load("./data/post-10");});
$(".myfix-11").click(function(){
$("#box").load("./data/post-11");});
$(".myfix-12").click(function(){
$("#box").load("./data/post-12");});
});
